services:
  postgres:
    image: 'postgres'
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - bantads
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: docker.io/dpage/pgadmin4
    ports:
      - 15432:80
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@email.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    networks:
      - bantads
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - bantads
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
    networks:
      - bantads

networks:
  bantads:
    external: true

volumes:
  postgres_data:
  pgadmin_data:
  mongo_data:
