services:
  postgres:
    image: 'postgres'
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - bantads
    volumes:
      - C:/Users/aalex/Downloads/bds/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s

  pgadmin:
    image: docker.io/dpage/pgadmin4
    ports:
      - 15432:80
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@email.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    networks:
      - bantads
    volumes:
      - C:/Users/aalex/Downloads/bds/pgadmin:/var/lib/pgadmin
    

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - bantads
    volumes:
      - C:/Users/aalex/Downloads/bds/mongo:/data/db

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
    networks:
      - bantads

networks:
  bantads:
    external: true
