FROM openjdk:17
ARG JAR_FILE=target/*.jar
COPY target/auth-*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-Dsprinamqp.deserialization.trustall", "-jar", "/app.jar"]